olx_market/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('market.urls')),
    path('user/', include('user.urls')),
    path('auth/', include("django.contrib.auth.urls")),
    path('appointment/', include('appointment.urls')),
    path('dashboard/', include("dashboard.urls")),
    path('product/', include("product.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.views.generic import TemplateView

app_name = "product"

urlpatterns = [
    path("", views.ProductListView.as_view(), name="products")
]

user/urls.py
"""Url conf for account related functionality"""
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "user"

urlpatterns = [
    path("register/",views.RegistrationView.as_view(template_name="user/register.html"),name="register"),
    path("login/",auth_views.LoginView.as_view(template_name="user/login.html"),name="login",),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("change-password/",views.PassView.as_view(template_name="user/password_change_form.html"),name="password-reset",),
    path("password-success/",views.PassSuccess.as_view(template_name="user/password_success.html"),name="password-success",),
    path("reset/<uidb64>/<token>/",auth_views.PasswordResetConfirmView.as_view(template_name="user/password_reset_confirm.html"),
        name="password_reset_confirm",
    ),
    path("reset/done/",auth_views.PasswordResetCompleteView.as_view(template_name="user/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("approve/", views.UserApproveView.as_view(), name="approve")
]

templates/partials/_css.html
{% load static %}

<link href="{% static 'olx_market/css/custom.css' %}" rel="stylesheet">
<link href="{% static 'olx_market/css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'olx_market/css/color.css' %}" rel="stylesheet">
<link href="{% static 'olx_market/css/responsive.css' %}" rel="stylesheet">
<link href="{% static 'olx_market/css/font-awesome.min.css' %}" rel="stylesheet">
<link href="{% static 'olx_market/css/prettyPhoto.css' %}" rel="stylesheet">
<link href="{% static 'olx_market/css/owl.carousel.min.css' %}" rel="stylesheet">
<link href="{% static 'olx_market/css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">
<link rel="icon" type="image/png" href="{% static 'olx_market/images/fav3.png' %}" />

templates/partials/_footer.html
{% load static %}
<footer class="footer">
  <div class="footer-widgets">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-6">
          <div class="widget"> <img class="ft-logo" src="{% static 'olx_market/images/footer_logo.png' %}" alt="">
            <p>OLX often covers other miscellaneous categories catering to a wide range of user needs and preferences. The platform's diverse categories provide users with a broad spectrum of options when buying or selling products and services.</p>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="widget">
            <h3>Our Services</h3>
            <ul>
              {% for service in services|slice:':8' %}
              <li><a href="{% url 'service_details' service.id %}"><i class="fa fa-arrow-right"></i>
                  {{service.title }}</a></li>
              {% endfor %}
            </ul>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="widget">
            <h3></h3>
            <ul>
              {% for Client in Clients|slice:':8' %}
              <li><a href="{% url 'Client_details' Client.id %}"><i class="fa fa-arrow-right"></i> {{ Client.name }}</a>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="widget">
            <h3>Contact</h3>
            <address>
              <ul>
                <li> <span class="icon"><i class="fa fa-map-marker" aria-hidden="true"></i></span> <span
                    class="add-text"><strong>Sandra Dhaneesh</strong> Trivandrum</span> </li>
                <li> <span class="icon"><i class="fa fa-phone-square" aria-hidden="true"></i></span> <span
                    class="add-text"><strong>Call at:</strong> +91 8113848852</span> </li>
                <li> <span class="icon"><i class="fa fa-envelope-o" aria-hidden="true"></i></span> <span
                    class="add-text"><strong>For Inquiry:</strong> info@olx.com</span> </li>

              </ul>
            </address>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-cr">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="footer-social"> <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a> <a href="#"><i
                class="fa fa-facebook" aria-hidden="true"></i></a> <a href="#"><i class="fa fa-google-plus"
                aria-hidden="true"></i></a> <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a> <a
              href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a>
          </div>
        </div>
        <div class="col-md-6">
          <p><strong>OLX</strong> © {% now 'Y' %}, All Rights Reserved</p>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/partials/_header.html
{% load static %}
<header class="site-header">
  <div class="top-bar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-8">
          <ul>
            <li><i class="fa fa-phone" aria-hidden="true"></i> Call at: <strong>+91 8113848852</strong></li>
            <li><i class="fa fa-envelope-o" aria-hidden="true"></i> Email : <strong>sandra@olx.com</strong>
            </li>
          </ul>
        </div>
        <div class="col-md-6 col-sm-4 top-social"> <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
          <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a> <a href="#"><i class="fa fa-google-plus"
              aria-hidden="true"></i></a> <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a> <a
            href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a> </div>
      </div>
    </div>
  </div>
  <div class="nav-logo-area">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <nav class="navbar navbar-default">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1" aria-expanded="false"> <span class="sr-only">Toggle
                  navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span
                  class="icon-bar"></span> </button>
              <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'olx_market/images/logo11.png' %}"
                  alt=""></a> </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li><a href="{% url 'index' %}">Home</a></li>
                </li>
                <li><a href="{% url 'services' %}">Services</a></li>
                <li><a href="{% url 'contact' %}">Contact</a></li>
              </ul>

              <ul class="nav navbar-nav navbar-right">
                <li><a class="appoint" href="{% url 'product:products' %}">Buy/Sell</a></li>
                <li> <a id="menu-toggle" href="#" class="toggle"><img src="{% static 'olx_market/images/bars.png' %}"
                      alt=""></a> </li>
              </ul>
            </div>
            <!-- /.navbar-collapse -->
          </nav>
        </div>
      </div>
    </div>
  </div>
</header>

templates/partials/_js.html
</div>
<!--Wrapper End-->
{% load static %}
<script src="{% static 'olx_market/js/jquery.min.js' %}"></script>
<script src="{% static 'olx_market/js/bootstrap.min.js' %}"></script>
<script src="{% static 'olx_market/js/js/jquery.prettyPhoto.js' %}"></script>
<script src="{% static 'olx_market/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'olx_market/js/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'olx_market/js/custom.js' %}"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-108110591-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];

  function gtag() {
    dataLayer.push(arguments);
  }
  gtag('js', new Date());

  gtag('config', 'UA-108110591-1');
</script>

templates/partials/_sidebar.html
{% load static %}
<div id="sidebar-wrapper">
  <a id="menu-close" href="#" class="close toggle"><i class="fa fa-times" aria-hidden="true"></i></a>
  <ul class="sidebar-nav">
    <li class="sidebar-brand"> <a href=""><img src="{% static 'olx_market/images/footer-logo.png' %}" alt=""></a> </li>
    <li><a href="{% url 'index' %}">Home</a></li>
    <li><a href="{% url 'services' %}">Services</a></li>
    <li><a href="{% url 'contact' %}">Contacts</a></li>
  </ul>
</div>

templates/partials/_slider.html
{% load static %}
<div class="main-slider">
    <div id="main-slider" class="owl-carousel owl-theme">
      {% for slider in sliders %}
      <div class="item">
          <div class="slide-caption slide-2">
            <div class="container">
              <h1>{{ slider.caption }}</h1>
              <p>{{ slider.slogan }}</p>
              <a class="btn-1" href="{% url 'user:login' %}">Login</a> <a class="btn-1" href="{% url 'user:register' %}">Sign Up</a>
            </div>
          </div>
          <span class="simg"><img src="{{ slider.image.url }}" alt=""></span>
        </div>
      {% endfor %}
    </div>
  </div>