dashboard/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.views.generic import TemplateView
from .decorators import admin_only

app_name = "dashboard"

urlpatterns = [
    path("", admin_only(views.UserListView.as_view()), name="dashboard")
]

olx_market/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('market.urls')),
    path('user/', include('user.urls')),
    path('auth/', include("django.contrib.auth.urls")),
    path('appointment/', include('appointment.urls')),
    path('dashboard/', include("dashboard.urls")),
    path('product/', include("product.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

user/urls.py
"""Url conf for account related functionality"""
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "user"

urlpatterns = [
    path("register/",views.RegistrationView.as_view(template_name="user/register.html"),name="register"),
    path("login/",auth_views.LoginView.as_view(template_name="user/login.html"),name="login",),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("change-password/",views.PassView.as_view(template_name="user/password_change_form.html"),name="password-reset",),
    path("password-success/",views.PassSuccess.as_view(template_name="user/password_success.html"),name="password-success",),
    path("reset/<uidb64>/<token>/",auth_views.PasswordResetConfirmView.as_view(template_name="user/password_reset_confirm.html"),
        name="password_reset_confirm",
    ),
    path("reset/done/",auth_views.PasswordResetCompleteView.as_view(template_name="user/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("approve/", views.UserApproveView.as_view(), name="approve")
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render
from django.views.generic import ListView

from user.models import OlxUser
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

class UserListView(ListView, LoginRequiredMixin):
    template_name = "dashboard/dashboard.html"
    model = OlxUser
    context_object_name = 'user_list'

templates/dashboard/content.html
{% extends 'dashboard.html' %}
{% block content %}
<div class="container mt-4">
 <div class="row">
   <div class="col-lg-3"><h1>Order <span class="badge bg-info">0</span></h1></div>
   <div class="col-lg-3"><h1>Products <span class="badge bg-info">0</span></h1></div>
   <div class="col-lg-3"><h1>Sales <span class="badge bg-info">0</span></h1></div>
   <div class="col-lg-3"><h1>Profit <span class="badge bg-info">0</span></h1></div>
 </div>
</div>
<div class="container mt-4">
<canvas id="myChart" width="100%" height="500px"></canvas>
</div>
<script>

        var ctx = document.getElementById("myChart").getContext("2d");
        var myChart = new Chart(ctx, {
            type: 'line',
            
            data: {
                labels: [1,2,3,4,5,6,7,8,9,10],
                datasets: [
                    {
                        label: "My First dataset",
                        data: [1,2,3,2,1,2,3,4,5,4],
                        fill: false,
                        borderColor: 'rgb(75, 192, 192)',
                        tension: 0.1
                    }
                ]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false
            }
        });
</script>

{% endblock content %}

templates/dashboard/dashboard.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}

<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>

  <script src="https://kit.fontawesome.com/ebd9a67ca3.js" crossorigin="anonymous"></script>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>


  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Ranchers&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'css/master.css' %}">
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/chart.js@3.5.1/dist/chart.min.js"></script>


</head>

<body>

  <style>
    @import url('https://fonts.googleapis.com/css2?family=Barlow&display=swap');

    body {
      font-family: 'Barlow', sans-serif;
    }

    .tick-link,
    .cross-link {
      display: inline-block;
      margin: 10px;
      padding: 10px;
      text-decoration: none;
      color: #fff;
      border-radius: 5px;
      cursor: pointer;
    }

    .tick-link {
      background-color: #4caf50;
      /* Green */
    }

    .cross-link {
      background-color: #f44336;
      /* Red */
    }

    a:hover {
      text-decoration: none;
    }

    .border-left {
      border-left: 2px solid var(--primary) !important;
    }


    .sidebar {
      top: 0;
      left: 0;
      z-index: 100;
      overflow-y: auto;
    }

    .overlay {
      background-color: rgb(0 0 0 / 45%);
      z-index: 99;
    }

    /* sidebar for small screens */
    @media screen and (max-width: 767px) {

      .sidebar {
        max-width: 18rem;
        transform: translateX(-100%);
        transition: transform 0.4s ease-out;
      }

      .sidebar.active {
        transform: translateX(0);
      }

    }

    /* generic */

    body {
      background-color: #eee;
      color: #444;
      font-family: sans-serif;
    }

    .list ul:nth-child(odd) {
      background-color: #ddd;
    }

    .list ul:nth-child(even) {
      background-color: #fff;
    }

    /* big */
    @media screen and (min-width:600px) {

      .list {
        display: table;
        margin: 1em;
      }

      .list ul {
        display: table-row;
      }

      .list ul:first-child li {
        background-color: #444;
        color: #fff;
      }

      .list ul>li {
        display: table-cell;
        padding: .5em 1em;
      }

    }

    /* small */
    @media screen and (max-width:599px) {

      .list ul {
        border: solid 1px #ccc;
        display: block;
        list-style: none;
        margin: 1em;
        padding: .5em 1em;
      }

      .list ul:first-child {
        display: none;
      }

      .list ul>li {
        display: block;
        padding: .25em 0;
      }

      .list ul:nth-child(odd)>li+li {
        border-top: solid 1px #ccc;
      }

      .list ul:nth-child(even)>li+li {
        border-top: solid 1px #eee;
      }

      .list ul>li:before {
        color: #000;
        content: attr(data-label);
        display: inline-block;
        font-size: 75%;
        font-weight: bold;
        text-transform: capitalize;
        vertical-align: top;
        width: 50%;
      }

      .list p {
        margin: -1em 0 0 50%;
      }

    }

    /* tiny */
    @media screen and (max-width:349px) {

      .list ul>li:before {
        display: block;
      }

      .list p {
        margin: 0;
      }

    }
  </style>
  <script>
    $(document).ready(() => {

      $('#open-sidebar').click(() => {

        // add class active on #sidebar
        $('#sidebar').addClass('active');

        // show sidebar overlay
        $('#sidebar-overlay').removeClass('d-none');

      });


      $('#sidebar-overlay').click(function () {

        // add class active on #sidebar
        $('#sidebar').removeClass('active');

        // show sidebar overlay
        $(this).addClass('d-none');

      });

    });

  </script>
  <!-- overlay -->
  <div id="sidebar-overlay" class="overlay w-100 vh-100 position-fixed d-none"></div>

  <!-- sidebar -->
  <div class="col-md-3 col-lg-2 px-0 position-fixed h-100 bg-white shadow-sm sidebar" id="sidebar">
    <h1 class="bi bi-bootstrap text-primary d-flex my-4 justify-content-center"></h1>
    <div class="list-group rounded-0">
      <a href="#" class="list-group-item list-group-item-action active border-0 d-flex align-items-center">
        <span class="bi bi-border-all"></span>
        <span class="ml-2">Dashboard</span>
      </a>
      <a href="#" class="list-group-item list-group-item-action border-0 align-items-center">
        <span class="bi bi-box"></span>
        <span class="ml-2">Products</span>
      </a>

      <button class="list-group-item list-group-item-action border-0 d-flex justify-content-between align-items-center"
        data-toggle="collapse" data-target="#sale-collapse">
        <div>
          <span class="bi bi-cart-dash"></span>
          <span class="ml-2">Sale</span>
        </div>
        <span class="bi bi-chevron-down small"></span>
      </button>
      <div class="collapse" id="sale-collapse" data-parent="#sidebar">
        <div class="list-group">
          <a href="#" class="list-group-item list-group-item-action border-0 pl-5">Customers</a>
          <a href="#" class="list-group-item list-group-item-action border-0 pl-5">Sales</a>
        </div>
      </div>

      <button class="list-group-item list-group-item-action border-0 d-flex justify-content-between align-items-center"
        data-toggle="collapse" data-target="#purchase-collapse">
        <div>
          <span class="bi bi-cart-plus"></span>
          <span class="ml-2">Purchase</span>
        </div>
        <span class="bi bi-chevron-down small"></span>
      </button>
      <div class="collapse" id="purchase-collapse" data-parent="#sidebar">
        <div class="list-group">
          <a href="#" class="list-group-item list-group-item-action border-0 pl-5">Sellers</a>
          <a href="#" class="list-group-item list-group-item-action border-0 pl-5">Purchases</a>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-9 col-lg-10 ml-md-auto px-0 ms-md-auto">
    <!-- top nav -->
    <nav class="w-100 d-flex px-4 py-2 mb-4 shadow-sm">
      <!-- close sidebar -->
      <button class="btn py-0 d-lg-none" id="open-sidebar">
        <span class="bi bi-list text-primary h3"></span>
      </button>
      <div class="dropdown ml-auto">
        <button class="btn py-0 d-flex align-items-center" id="logout-dropdown" data-toggle="dropdown"
          aria-expanded="false">
          <span class="bi bi-person text-primary h4"></span>
          <span class="bi bi-chevron-down ml-1 mb-2 small"></span>
        </button>
        <div class="dropdown-menu dropdown-menu-right border-0 shadow-sm" aria-labelledby="logout-dropdown">
          <a class="dropdown-item" href="#">Logout</a>
          <a class="dropdown-item" href="#">Settings</a>
        </div>
      </div>
    </nav>

    <!-- main content -->
    <main class="p-4 min-vh-100">
      <section class="row">
        <div class="col-md-6 col-lg-4">
          <!-- card -->
          <article class="p-4 rounded shadow-sm border-left
       mb-4">
            <a href="#" class="d-flex align-items-center">
              <span class="bi bi-box h5"></span>
              <h5 class="ml-2">Products</h5>
            </a>
          </article>
        </div>
        <div class="col-md-6 col-lg-4">
          <article class="p-4 rounded shadow-sm border-left mb-4">
            <a href="#" class="d-flex align-items-center">
              <span class="bi bi-person h5"></span>
              <h5 class="ml-2">Customers</h5>
            </a>
          </article>
        </div>
        <div class="col-md-6 col-lg-4">
          <article class="p-4 rounded shadow-sm border-left mb-4">
            <a href="#" class="d-flex align-items-center">
              <span class="bi bi-person-check h5"></span>
              <h5 class="ml-2">Sellers</h5>
            </a>
          </article>
        </div>
      </section>

      <div class="jumbotron jumbotron-fluid rounded bg-white border-0 shadow-sm border-left px-4">
        <div class="container">

          <div class="list">
            <ul>
              <li>First Name</li>
              <li>Last Name</li>
              <li>Country</li>
              <li>Number</li>
              <li>Email</li>
              <li>State</li>
              <li>District</li>
              <li>Approve</li>
            </ul>
            {% for user in user_list %}
            <ul>
              <li data-label="first name">{{user.olxuserprofile.firstname}}</li>
              <li data-label="last name">{{user.olxuserprofile.lastname}}</li>
              <li data-label="country">{{user.olxuserprofile.country}}</li>
              <li data-label="number">{{user.olxuserprofile.phone}}</li>
              <li data-label="email">{{user.email}}</li>
              <li data-label="email">{{user.olxuserprofile.state}}</li>
              <li data-label="email">{{user.olxuserprofile.district}}</li>
              {% if user.is_approved == '0' %}
              <li data-label="email"><a href="{% url 'user:approve' %}?id={{ user.id }}&approve=1"
                  class="tick-link">✔</a>
                <a href="{% url 'user:approve' %}?id={{ user.id }}&approve=2" class="cross-link">✘</a>
              </li>
              {% elif user.is_approved == '1' %}
              <li data-label="email"><span class="tick-link">Approved</span></li>
                  
              {% else %}
              <li data-label="email"><span class="cross-link">Rejected</span></li>
              {% endif %}
            </ul>
            {% endfor %}
          </div>
        </div>
      </div>
    </main>
  </div>




</body>

</html>

templates/dashboard/navbar1.html
  {% load static %}
  {% block horizontal-nav %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'dashboard:dashboard' %}">
        <img src="{% static 'images/shop_icon.png' %}" alt="shop-icon" width="32" class="mb-2">
        ShoppingCart
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          {% comment %} User {% endcomment %}
          <li class="nav-item dropdown dropstart">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              <i class="fas fa-user"></i>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% if user.is_authenticated %}
              <li><a class="dropdown-item" href="{% url 'user:logout' %}">Logout</a></li>
              {% else %}
              <li><a class="dropdown-item" href="#">Login</a></li>
              {% endif %}
              
            </ul>
          </li>
        </li>


        </ul>

      </div>
    </div>
  </nav>
{% endblock horizontal-nav %}

templates/dashboard/sidebar.html
{% load static %}
{% block sidebar %}
<style>
  @import url("https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap");

  * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: "Poppins", sans-serif;
  }

  /* nav and sidebar ---------------------------------------------------------------------------------------------- */
  nav {
    width: 100%;
    background: #000;
    color: #fff;
    display: flex;
    align-items: center;
    font-size: 18px;
    height: 70px;
    justify-content: space-between;
    position: relative;
    padding: 0 20px;
  }

  .profilre_dropdown {
    padding: 10px 20px;
    z-index: 9999;
    box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;
    position: absolute;
    top: 60px;
    right: 5px;
    background-color: #fff;
    color: black;
    display: none;
  }

  .toggle_profile_dropdown {
    display: block;
  }

  .profilre_dropdown ul {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  .profilre_dropdown ul li {
    list-style: none;
  }

  .profilre_dropdown ul li a {
    color: black;
    text-decoration: none;
  }

  nav img {
    border: 2px solid black;
    padding: 5px 10px;
    width: 150px;
  }

  nav img:hover {
    border: 2px solid #fff;
  }

  nav .searchbar {
    display: flex;
    gap: 0;
  }

  nav .searchbar button {
    border: none;
    outline: none;
    border-top-right-radius: 5px;
    border-bottom-right-radius: 5px;
    font-size: 20px;
    padding: 0 15px;
    background-color: rgb(242, 242, 182);
  }

  nav input {
    width: 900px;
    height: 40px;
    border-right: none;
    border-top-left-radius: 5px;
    border-bottom-left-radius: 5px;
    border: none;
    outline: none;
    padding: 0 10px;
    font-size: 18px;
  }

  nav a {
    text-decoration: none;
    color: #fff;
  }

  nav .links {
    display: flex;
    gap: 20px;
    font-size: 30px;

  }

  .links i {
    cursor: pointer
  }

  .bell,
  .cart {
    position: relative
  }

  .links span {
    position: absolute;
    font-size: 15px;
    width: 20px;
    height: 20px;
    background: orange;
    color: black;
    border-radius: 50%;
    text-align: center;
    font-weight: bold;
    left: 20px;
    cursor: pointer;


  }

  .bell span {
    left: 15px
  }

  .nav2 {
    display: flex;
    background-color: #232f3e;
    height: 50px;
    align-items: center;
    justify-content: space-between;
    padding: 0 30px;
  }

  .nav2 ul {
    display: flex;
    gap: 15px;
    align-items: center;

  }

  .nav2 ul li {
    list-style: none;
  }

  .nav2 ul li a {
    text-decoration: none;
    color: #fff;
    font-size: 15px;
    border: 1px solid #232f3e;
    padding: 5px 8px;
  }

  .nav2 ul li a:hover,
  .nav2 .menu:hover,
  .nav2 .downloadApp a:hover {
    border: 1px solid #fff;
  }

  .nav2 .menu {
    color: #fff;
    font-size: 20px;
    cursor: pointer;
    border: 1px solid #232f3e;
    padding: 5px 8px;
  }

  .nav2 .downloadApp a {
    text-decoration: none;
    color: #fff;
    font-size: 18px;
    border: 1px solid #232f3e;
    padding: 5px 8px;
  }

  .sidebar {
    top: 0;
    background-color: #fff;
    color: black;
    position: fixed;
    left: -100%;
    height: 100vh;
    width: 400px;
    display: flex;
    flex-direction: column;
    gap: 20px;
    box-shadow: rgba(0, 0, 0, 0.15) 1.95px 1.95px 2.6px;
    overflow-y: scroll;
    transition: 0.3s;
    z-index: 999;
  }

  .sidebar .top {
    padding: 10px 30px;
    background-color: #232f3e;
    color: #fff;
    font-size: 25px;
    font-weight: bold;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .sidebar .top button {
    background: transparent;
    border: none;
    outline: none;
    color: #fff;
    font-size: 25px;
    cursor: pointer;
  }

  .sidebar ul {
    padding: 0 30px;
    display: flex;
    flex-direction: column;
    gap: 20px;
    font-size: 20px;
  }

  .sidebar ul .title {
    font-weight: bold;
    font-size: 22px;
  }

  .sidebar ul li {
    list-style: none;
  }

  .sidebar ul li a {
    color: #000;
    text-decoration: none;
  }

  .show {
    left: 0;
  }




  /* main */



  @media only screen and (max-width: 1760px) {

    .nav2 ul li:nth-last-of-type(1),
    .nav2 ul li:nth-last-of-type(2),
    .nav2 ul li:nth-last-of-type(3) {
      display: none;
    }
  }

  @media only screen and (max-width: 1440px) {
    .nav2 .downloadApp a {
      font-size: 15px;
    }

    .nav2 {
      padding: 0 10px;
    }

    .nav2 ul {
      display: flex;
      gap: 0;
    }

    .nav2 ul li a {
      font-size: 13px;
    }
  }

  @media only screen and (max-width: 1288px) {
    nav input {
      width: 600px;
    }
  }

  @media only screen and (max-width: 1105px) {

    .nav2 ul li:nth-last-of-type(1),
    .nav2 ul li:nth-last-of-type(2),
    .nav2 ul li:nth-last-of-type(3),
    .nav2 ul li:nth-last-of-type(4),
    .nav2 ul li:nth-last-of-type(5) {
      display: none;
    }
  }

  @media only screen and (max-width: 1024px) {
    nav input {
      width: 600px;
    }

    .nav2 ul {
      display: flex;
      gap: 0;
    }
  }

  @media only screen and (max-width: 998px) {
    nav input {
      width: 400px;
    }

    .nav2 ul {
      display: none;
    }
  }

  @media only screen and (max-width: 804px) {
    nav input {
      width: 300px;
    }

    nav img {
      width: 100px;
    }

    nav .links {
      gap: 15px;
      font-size: 20px;
    }
  }

  @media only screen and (max-width: 692px) {
    nav input {
      width: 200px;
      height: 30px;
    }

    nav .searchbar button {
      font-size: 15px;
    }
  }

  @media only screen and (max-width: 498px) {
    nav input {
      width: 150px;
    }

    nav img {
      width: 70px;
    }

    nav .links {
      gap: 10px;
      font-size: 15px;
    }
  }

  @media only screen and (max-width: 426px) {
    nav {
      padding: 0 10px;
    }

    .nav2 .menu {
      font-size: 15px;
      padding: 3px 5px;
    }

    .nav2 .downloadApp a {
      text-decoration: none;
      color: #fff;
      font-size: 14px;
      padding: 3px 5px;
    }

    .sidebar {
      left: -120%;
    }

    .show {
      left: 0;
    }

    .sidebar {
      width: 100%;
      gap: 15px;
    }

    .sidebar .top {
      padding: 10px 30px;
      background-color: #232f3e;
      font-size: 20px;
      font-weight: bold;
    }

    .sidebar .top button {
      font-size: 20px;
    }

    .sidebar ul {
      padding: 0 15px;
      gap: 15px;
      font-size: 15px;
    }

    .sidebar ul .title {
      font-weight: bold;
      font-size: 22px;
    }

    .nav2 .menu {
      border: none;
      padding: 0;
      font-size: 13px;
    }

    .nav2 .downloadApp a {
      font-size: 13px;
      border: none;
      padding: 0;
    }

    nav .links div:nth-of-type(1),
    nav .links div:nth-of-type(3) {
      display: none;
    }
  }
</style>
<script>
  Array.from(document.getElementsByClassName("showbtn")).map((btn) => {
    btn.addEventListener("click", () => {
      console.log("click")
      document.getElementById("sidemenu").classList.toggle("show")
    })
  })

  document.getElementById("profile_dropdown").addEventListener("click", () => {
    document.getElementsByClassName("profilre_dropdown")[0].classList.toggle("toggle_profile_dropdown")
  })
</script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
  integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />
<section class="nav__side">
  <nav>
    <div class="barand"><img src="https://i.postimg.cc/FH1Qcjqg/whiteamazon.png" alt=""></div>
    <div class="searchbar">
      <input type="text">
      <button><i class="fa-solid fa-magnifying-glass"></i></button>
    </div>
    <div class="links">
      <div class="bell">
        <i class="fa-solid fa-bell"></i>
        <span>3</span>
      </div>
      <div class="cart">
        <i class="fa-solid fa-cart-shopping"></i>
        <span>5</span>
      </div>
      <div class="user" id="profile_dropdown">
        <i class="fa-regular fa-circle-user"></i>
      </div>
    </div>
    <div class="profilre_dropdown">
      <ul>
        <li><a href="#">My Profile</a></li>
        <li><a href="#">Sign in</a></li>
      </ul>
    </div>
  </nav>
  <div class="nav2">
    <div class="menu showbtn">
      <i class="fa-solid fa-bars "></i>
      <span>All</span>
    </div>
    <div>
      <ul>
        <li><a href="#">Amazon miniTv</a></li>
        <li><a href="#">Sell</a></li>
        <li><a href="#">Best Sellers</a></li>
        <li><a href="#">Today's Deal</a></li>
        <li><a href="#">Mobiles</a></li>
        <li><a href="#">New Release</a></li>
        <li><a href="#">Customer Service</a></li>
        <li><a href="#">Prime</a></li>
        <li><a href="#">Electronics</a></li>
        <li><a href="#">Gift ideas</a></li>
        <li><a href="#">Home & Kitchen</a></li>
      </ul>
    </div>
    <div class="downloadApp">
      <a href="#"> Shoping Make Easy | Download the app</a>
    </div>
  </div>
  <div class="sidebar" id="sidemenu">
    <div class="top">
      <div><i class="fa-regular fa-circle-user"></i>
        <span>Hello, sign in</span>
      </div>
      <div> <button class="showbtn"><i class="fa-solid fa-xmark"></i></button></div>
    </div>
    <ul>
      <li>
        <div class="title">Trending</div>
      </li>
      <li><a href="#">Best Seller</a></li>
      <li><a href="#">New Release</a></li>
      <li><a href="#">Movers and Shakers</a></li>
    </ul>
    <hr>
    <ul>
      <li>
        <div class="title">Digital contetn And Divices</div>
      </li>
      <li><a href="#">Best Seller</a></li>
      <li><a href="#">New Release</a></li>
      <li><a href="#">Movers and Shakers</a></li>
    </ul>
    <hr>
    <ul>
      <li>
        <div class="title">Shop by category</div>
      </li>
      <li><a href="#">Best Seller</a></li>
      <li><a href="#">New Release</a></li>
      <li><a href="#">Movers and Shakers</a></li>
    </ul>
    <hr>
    <ul>
      <li>
        <div class="title">Programs & Features</div>
      </li>
      <li><a href="#">Best Seller</a></li>
      <li><a href="#">New Release</a></li>
      <li><a href="#">Movers and Shakers</a></li>
    </ul>
    <hr>
    <ul>
      <li>
        <div class="title">Help & settings</div>
      </li>
      <li><a href="#">Best Seller</a></li>
      <li><a href="#">New Release</a></li>
      <li><a href="#">Movers and Shakers</a></li>
    </ul>
  </div>
</section>


{% endblock sidebar %}